(() => {
  const resultRoot = document.getElementById("results");
  const summary = document.getElementById("summary");
  const frame = document.getElementById("appFrame");
  const fixtureNames = ["roundtrip-policy.xml", "unsupported-policy.xml"];
  const waitForApp = () => new Promise((resolve, reject) => { const timeout = setTimeout(() => reject(new Error("Application frame did not become ready")), 5000); const finish = () => { clearTimeout(timeout); resolve(); }; if (frame.contentDocument?.readyState === "complete") finish(); else frame.addEventListener("load", finish, { once: true }); });
  const callApp = (() => { let nextId = 0; const pending = new Map(); window.addEventListener("message", event => { if (event.data?.type !== "policy-studio-test-result") return; const request = pending.get(event.data.id); if (!request) return; pending.delete(event.data.id); event.data.ok ? request.resolve(event.data.value) : request.reject(new Error(event.data.error || "Application test operation failed")); }); return (method, payload) => new Promise((resolve, reject) => { const id = `request-${++nextId}`; pending.set(id, { resolve, reject }); frame.contentWindow.postMessage({ type: "policy-studio-test", id, method, payload }, "*"); setTimeout(() => { if (pending.delete(id)) reject(new Error(`Timed out waiting for ${method}`)); }, 5000); }); })();
  // Compare only the editable/serializable model. Import diagnostics are
  // intentionally omitted because a policy can retain supported rules while
  // also carrying warnings about unsupported XML that must be reviewed.
  const projection = policy => ({ collections: Object.fromEntries(Object.entries(policy.collections).map(([type, collection]) => [type, { mode: collection.mode, extensionsXml: collection.extensionsXml || "", rules: collection.rules.map(rule => ({ id: rule.id, name: rule.name, action: rule.action, sid: rule.sid, kind: rule.kind, condition: rule.condition, exceptions: rule.exceptions || [] })) }])), policyExtensionsXml: policy.policyExtensionsXml || "" });
  function report(name, passed, detail) { const item = document.createElement("div"); item.className = `result ${passed ? "pass" : "fail"}`; item.textContent = `${passed ? "PASS" : "FAIL"}  ${name}${detail ? ` — ${detail}` : ""}`; resultRoot.appendChild(item); return passed; }
  async function run() {
    try {
      await waitForApp(); let passed = 0; let total = 0;
      for (const fixtureName of fixtureNames) {
        const text = await fetch(`fixtures/${fixtureName}`).then(response => { if (!response.ok) throw new Error(`${response.status} ${response.statusText}`); return response.text(); });
        await callApp("reset"); await callApp("importXml", text); const imported = await callApp("snapshot"); const exported = await callApp("serializeXml"); await callApp("reset"); await callApp("importXml", exported); const reimported = await callApp("snapshot");
        const equal = JSON.stringify(projection(imported)) === JSON.stringify(projection(reimported)); total++; passed += report(`${fixtureName} import → export → import`, equal, equal ? "semantic model preserved" : "semantic model changed");
        if (fixtureName === "roundtrip-policy.xml") { const hasExceptions = imported.collections.Exe.rules.some(rule => rule.exceptions?.length); const hasExtensions = Boolean(imported.collections.Exe.extensionsXml && imported.policyExtensionsXml); total += 2; passed += report("exceptions preserved", hasExceptions && reimported.collections.Exe.rules.some(rule => rule.exceptions?.length)); passed += report("extensions preserved", hasExtensions && Boolean(reimported.collections.Exe.extensionsXml && reimported.policyExtensionsXml)); }
        if (fixtureName === "unsupported-policy.xml") { const blocked = imported.importIssues.length > 0; total++; passed += report("unsupported content blocks export", blocked, `${imported.importIssues.length} issue(s) reported`); }
      }
      const msiMetadata = await callApp("parseMsiMetadata", Array.from(window.__msiSummaryFixture())); const msiPassed = msiMetadata.detected && msiMetadata.parseStatus === "parsed" && msiMetadata.title === "Contoso Installer" && msiMetadata.author === "Contoso Ltd" && msiMetadata.applicationName === "Windows Installer"; total++; passed += report("MSI SummaryInformation metadata parsed", msiPassed, msiPassed ? "title, author, and application extracted" : `status ${msiMetadata.parseStatus || "unknown"}`);
      const scriptText = await fetch("fixtures/sample.ps1").then(response => response.text()); const scriptBytes = Array.from(new TextEncoder().encode(scriptText)); const scriptAnalysis = await callApp("analyzeFixture", { name: "sample.ps1", bytes: scriptBytes }); const scriptPassed = scriptAnalysis.fileType === "Script" && scriptAnalysis.script?.detected && scriptAnalysis.script.requires?.includes("-Version 5.1") && scriptAnalysis.hashBasis === "whole-file SHA-256"; total++; passed += report("PowerShell script metadata parsed", scriptPassed, scriptPassed ? "extension, #requires, and local hash captured" : `type ${scriptAnalysis.fileType || "unknown"}`);
      const dllFixture = await fetch("fixtures/dll-analysis.json").then(response => { if (!response.ok) throw new Error(`${response.status} ${response.statusText}`); return response.json(); }); const dllClassification = await callApp("classifyFileName", dllFixture.name); const dllPassed = dllClassification.fileType === dllFixture.expectedFileType && dllClassification.targetCollection === dllFixture.expectedTargetCollection; total++; passed += report("DLL analysis routes to DLL collection", dllPassed, dllPassed ? "DLL hash and publisher proposals target Dll" : `type ${dllClassification.fileType || "unknown"} → ${dllClassification.targetCollection || "unknown"}`);
      const truncatedFixture = await fetch("fixtures/truncated-pe.json?rev=2").then(response => response.json()); const truncatedAnalysis = await callApp("analyzeFixture", { name: truncatedFixture.name, bytes: truncatedFixture.bytes }); const truncatedPassed = truncatedAnalysis.fileType === truncatedFixture.expectedFileType && truncatedAnalysis.appLockerHash === truncatedFixture.expectedHash; total++; passed += report("Truncated PE is rejected safely", truncatedPassed, truncatedPassed ? "no rule candidate generated" : `type ${truncatedAnalysis.fileType || "unknown"}`);
      const validationReport = await callApp("buildValidationReport"); const reportPassed = validationReport.schemaVersion === 1 && Array.isArray(validationReport.collections) && Array.isArray(validationReport.findings) && typeof validationReport.exportReady === "boolean"; total++; passed += report("Validation report is versioned and structured", reportPassed, reportPassed ? "JSON report includes export readiness" : "report shape was unexpected");
      const appxAnalysis = await callApp("analyzeFixture", { name: "contoso.msix", bytes: Array.from(window.__appxFixture()) }); const appxPassed = appxAnalysis.fileType === "Appx" && appxAnalysis.appx?.parseStatus === "parsed" && appxAnalysis.appx.publisher === "CN=Contoso Ltd, O=Contoso" && appxAnalysis.appx.version === "2.4.1.0" && appxAnalysis.appLockerHash === null; total++; passed += report("AppX manifest metadata parsed", appxPassed, appxPassed ? "identity, version, and publisher extracted" : `status ${appxAnalysis.appx?.parseStatus || "unknown"}`);
     const simulation = await callApp("simulatePolicy", { collection: "Exe", path: "%WINDIR%\\System32\\cmd.exe", sid: "S-1-1-0" }); const simulationPassed = simulation.decision === "Allowed" && simulation.matches?.length > 0; total++; passed += report("What-if simulator evaluates path rules", simulationPassed, simulationPassed ? "matching allow returned" : `decision ${simulation.decision || "unknown"}`);
     const samePolicy = await callApp("snapshot"); const diff = await callApp("semanticDiff", samePolicy); const diffPassed = Array.isArray(diff) && diff.length === 0; total++; passed += report("Semantic diff detects identical policies", diffPassed, diffPassed ? "no false positives" : `${diff.length} unexpected change(s)`);
     const appControlFindings = await callApp("appControlFindings"); const appControlPassed = Array.isArray(appControlFindings) && appControlFindings.length > 0; total++; passed += report("App Control readiness review returns findings", appControlPassed, appControlPassed ? "advisory migration guidance available" : "no findings returned");
      const safety = await callApp("safetyFindings"); const safetyPassed = Array.isArray(safety) && safety.some(item => /may be blocked/.test(item[1])); total++; passed += report("Safety checks flag missing built-in coverage", safetyPassed, safetyPassed ? "lockout warning returned" : "expected gotcha was not detected");
     summary.textContent = `${passed}/${total} checks passed`;
      summary.style.color = passed === total ? "#2f6b53" : "#a64e45";
    } catch (error) { summary.textContent = `Harness failed: ${error.message}`; summary.style.color = "#a64e45"; report("harness startup", false, error.message); }
  }
  run();
})();
